/*
 * Julianne Wojdak
 * 05/12/18
 * Software for Zirboin Bank
 */

/**
 *
 * @author JuWoj8013
 */
public class FormPlanetZirboin extends javax.swing.JFrame {

    /**
     * Creates new form FormPlanetZirboin
     */
    public FormPlanetZirboin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        HeadingLabel = new javax.swing.JLabel();
        UserInputLabel = new javax.swing.JLabel();
        UserInputText = new javax.swing.JTextField();
        UserOutputLabel = new javax.swing.JLabel();
        DrobzitsOutputLabel = new javax.swing.JLabel();
        DrobzitsLabel = new javax.swing.JLabel();
        ClickwicksOutputLabel = new javax.swing.JLabel();
        ClickwicksLabel = new javax.swing.JLabel();
        GazoontightsOutputLabel = new javax.swing.JLabel();
        GazoontightsLabel = new javax.swing.JLabel();
        FrazointsOutputLabel = new javax.swing.JLabel();
        FrazointsLabel = new javax.swing.JLabel();
        BlointointsOutputLabel = new javax.swing.JLabel();
        BlointointsLabel = new javax.swing.JLabel();
        VrobitsLabel = new javax.swing.JLabel();
        EnterButton = new javax.swing.JButton();
        OutputLabel = new javax.swing.JLabel();
        VrobitsOutputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        HeadingLabel.setFont(new java.awt.Font("256 Bytes", 0, 36)); // NOI18N
        HeadingLabel.setText("Planet Zirboin");

        UserInputLabel.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        UserInputLabel.setText("Enter your vrobits:");

        UserInputText.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N

        UserOutputLabel.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        UserOutputLabel.setText("You have:");

        DrobzitsOutputLabel.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N

        DrobzitsLabel.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        DrobzitsLabel.setText("Drobzits");

        ClickwicksOutputLabel.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N

        ClickwicksLabel.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        ClickwicksLabel.setText("Clickwicks");

        GazoontightsOutputLabel.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N

        GazoontightsLabel.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        GazoontightsLabel.setText("Gazoontights");

        FrazointsOutputLabel.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N

        FrazointsLabel.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        FrazointsLabel.setText("Frazoints");

        BlointointsOutputLabel.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N

        BlointointsLabel.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        BlointointsLabel.setText("Blointoints");

        VrobitsLabel.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        VrobitsLabel.setText("Vrobits");

        EnterButton.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N
        EnterButton.setText("Enter");
        EnterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterButtonActionPerformed(evt);
            }
        });

        OutputLabel.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N

        VrobitsOutputLabel.setFont(new java.awt.Font("AachenDEEMed", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(HeadingLabel)
                .addGap(95, 95, 95))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ClickwicksOutputLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                                .addComponent(DrobzitsOutputLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(BlointointsOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VrobitsOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GazoontightsOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FrazointsOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ClickwicksLabel)
                                    .addComponent(DrobzitsLabel))
                                .addGap(18, 18, 18)
                                .addComponent(OutputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GazoontightsLabel)
                                    .addComponent(FrazointsLabel)
                                    .addComponent(BlointointsLabel)
                                    .addComponent(VrobitsLabel))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(UserInputLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UserInputText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EnterButton)))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(UserOutputLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(HeadingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(UserInputLabel)
                                    .addComponent(UserInputText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(EnterButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UserOutputLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(DrobzitsOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(DrobzitsLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ClickwicksOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ClickwicksLabel)))
                                    .addComponent(OutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GazoontightsLabel))
                            .addComponent(GazoontightsOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addComponent(FrazointsLabel))
                    .addComponent(FrazointsOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BlointointsLabel)
                    .addComponent(BlointointsOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VrobitsLabel)
                    .addComponent(VrobitsOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterButtonActionPerformed
        //Variables
        int numV;  //Number of vrobits
        int numD;  //Number of drobzits
        int numC;  //Number of clickwicks
        int numG;  //Number of gazoontights
        int numF;  //Number of frazoints
        int numB;  //Number of blointoints
        int numVR; //Remaining number of vrobits
        
        //User input
        numV = Integer.parseInt(UserInputText.getText());
        
        //Calculations
        numD = numV/100000;
        numVR = numV-numD*100000;
        numC = numVR/50000;
        numVR = numVR-numC*50000;
        numG = numVR/10000;
        numVR = numVR-numG*10000;
        numF = numVR/1000;
        numVR = numVR-numF*1000;
        numB = numVR/500;
        numVR = numVR-numB*500;
        numVR = numVR;
        
        //Output
        DrobzitsOutputLabel.setText("" + numD);
        ClickwicksOutputLabel.setText("" + numC);
        GazoontightsOutputLabel.setText("" + numG);
        FrazointsOutputLabel.setText("" + numF);
        BlointointsOutputLabel.setText("" + numB);
        VrobitsOutputLabel.setText("" + numVR);
        OutputLabel.setText("Thank you for choosing Zirboin Bank!");
        
    }//GEN-LAST:event_EnterButtonActionPerformed

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPlanetZirboin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPlanetZirboin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BlointointsLabel;
    private javax.swing.JLabel BlointointsOutputLabel;
    private javax.swing.JLabel ClickwicksLabel;
    private javax.swing.JLabel ClickwicksOutputLabel;
    private javax.swing.JLabel DrobzitsLabel;
    private javax.swing.JLabel DrobzitsOutputLabel;
    private javax.swing.JButton EnterButton;
    private javax.swing.JLabel FrazointsLabel;
    private javax.swing.JLabel FrazointsOutputLabel;
    private javax.swing.JLabel GazoontightsLabel;
    private javax.swing.JLabel GazoontightsOutputLabel;
    private javax.swing.JLabel HeadingLabel;
    private javax.swing.JLabel OutputLabel;
    private javax.swing.JLabel UserInputLabel;
    private javax.swing.JTextField UserInputText;
    private javax.swing.JLabel UserOutputLabel;
    private javax.swing.JLabel VrobitsLabel;
    private javax.swing.JLabel VrobitsOutputLabel;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
